-- V1.5__create_accounts_schema.sql
-- Account schema for Corporate & SME Banking System
-- Created in Flyway so that V4 can reference accounts table.
-- Hibernate uses existing tables (doesn't recreate if they exist).

CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(50) NOT NULL UNIQUE,
    account_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    balance NUMERIC(19,2),
    customer_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_version_id BIGINT,
    product_name VARCHAR(255),
    opened_at TIMESTAMP NOT NULL,
    closed_at TIMESTAMP,
    version BIGINT DEFAULT 0,
    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255)
);

CREATE INDEX idx_accounts_account_number ON accounts(account_number);
CREATE INDEX idx_accounts_customer_id ON accounts(customer_id);
CREATE INDEX idx_accounts_status ON accounts(status);
CREATE INDEX idx_accounts_product_version_id ON accounts(product_version_id);

CREATE TABLE current_account (
    id BIGINT PRIMARY KEY REFERENCES accounts(id),
    overdraft_limit NUMERIC(19,2),
    interest_rate NUMERIC(5,2)
);

CREATE TABLE savings_account (
    id BIGINT PRIMARY KEY REFERENCES accounts(id),
    minimum_balance NUMERIC(19,2),
    interest_rate NUMERIC(5,2),
    last_interest_posted DATE
);

CREATE TABLE fixed_deposit_account (
    id BIGINT PRIMARY KEY REFERENCES accounts(id),
    deposit_term INTEGER,
    maturity_date DATE,
    maturity_amount NUMERIC(19,2)
);

CREATE TABLE loan_account (
    id BIGINT PRIMARY KEY REFERENCES accounts(id),
    loan_amount NUMERIC(19,2),
    interest_rate NUMERIC(5,2),
    term INTEGER,
    outstanding_balance NUMERIC(19,2),
    next_payment_date DATE
);
