-- V1.6__create_account_holders_schema.sql
-- Account holder associations for Corporate & SME Banking System

CREATE TABLE account_holders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    role VARCHAR(30) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255)
);

CREATE INDEX idx_account_holders_account_id ON account_holders(account_id);
CREATE INDEX idx_account_holders_customer_id ON account_holders(customer_id);
ALTER TABLE account_holders ADD CONSTRAINT uk_account_holder_account_customer UNIQUE (account_id, customer_id);
