-- V10__create_limits_schema.sql
-- Create unified limits schema per design spec

CREATE TABLE product_limits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    limit_definition_id BIGINT NOT NULL REFERENCES limit_definitions(id),
    product_code VARCHAR(50) NOT NULL,
    override_amount DECIMAL(19, 4),
    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    UNIQUE (limit_definition_id, product_code)
);

CREATE INDEX idx_product_limits_product_code ON product_limits(product_code);

CREATE TABLE customer_limits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    limit_definition_id BIGINT NOT NULL REFERENCES limit_definitions(id),
    customer_id BIGINT NOT NULL,
    override_amount DECIMAL(19, 4),
    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    UNIQUE (limit_definition_id, customer_id)
);

CREATE INDEX idx_customer_limits_customer_id ON customer_limits(customer_id);

CREATE TABLE account_limits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    limit_definition_id BIGINT NOT NULL REFERENCES limit_definitions(id),
    account_number VARCHAR(50) NOT NULL,
    override_amount DECIMAL(19, 4),
    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    UNIQUE (limit_definition_id, account_number)
);

CREATE INDEX idx_account_limits_account_number ON account_limits(account_number);

CREATE TABLE approval_thresholds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    limit_definition_id BIGINT NOT NULL UNIQUE REFERENCES limit_definitions(id),
    absolute_amount DECIMAL(19, 4),
    percentage_of_limit INTEGER,
    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255)
);

CREATE TABLE limit_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    limit_definition_id BIGINT NOT NULL REFERENCES limit_definitions(id),
    account_number VARCHAR(50) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    cumulative_amount DECIMAL(19, 4) NOT NULL DEFAULT 0,
    UNIQUE (limit_definition_id, account_number, period_start)
);

CREATE INDEX idx_limit_usage_account_number ON limit_usage(account_number);

CREATE TABLE approval_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    limit_definition_id BIGINT NOT NULL REFERENCES limit_definitions(id),
    transaction_reference VARCHAR(100),
    amount DECIMAL(19, 4),
    currency VARCHAR(3),
    account_number VARCHAR(50),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    rejection_reason VARCHAR(500),
    approved_by VARCHAR(255),
    decision_at TIMESTAMP,
    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255)
);

CREATE INDEX idx_approval_requests_status ON approval_requests(status);
CREATE INDEX idx_approval_requests_account_number ON approval_requests(account_number);
