-- V12__create_charges_schema.sql
-- Create charges management tables

-- Charge Definitions table
CREATE TABLE charge_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) UNIQUE NOT NULL,
    charge_type VARCHAR(30) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255)
);

CREATE INDEX idx_charge_definitions_charge_type ON charge_definitions(charge_type);

-- Charge Rules table
CREATE TABLE charge_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    charge_definition_id BIGINT NOT NULL,
    calculation_method VARCHAR(20) NOT NULL,
    flat_amount DECIMAL(19,4),
    percentage_rate DECIMAL(10,6),
    min_amount DECIMAL(19,4),
    max_amount DECIMAL(19,4),
    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    CONSTRAINT fk_charge_rules_charge_definition FOREIGN KEY (charge_definition_id) REFERENCES charge_definitions(id)
);

CREATE INDEX idx_charge_rules_charge_definition_id ON charge_rules(charge_definition_id);

-- Charge Tiers table
CREATE TABLE charge_tiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    charge_rule_id BIGINT NOT NULL,
    tier_from BIGINT NOT NULL,
    tier_to BIGINT,
    rate DECIMAL(19,6) NOT NULL,
    CONSTRAINT fk_charge_tiers_charge_rule FOREIGN KEY (charge_rule_id) REFERENCES charge_rules(id) ON DELETE CASCADE
);

CREATE INDEX idx_charge_tiers_charge_rule_id ON charge_tiers(charge_rule_id);

-- Product Charges table
CREATE TABLE product_charges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    charge_definition_id BIGINT NOT NULL,
    product_code VARCHAR(50) NOT NULL,
    override_amount DECIMAL(19,4),
    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    CONSTRAINT fk_product_charges_charge_definition FOREIGN KEY (charge_definition_id) REFERENCES charge_definitions(id),
    CONSTRAINT uk_product_charges_charge_product UNIQUE (charge_definition_id, product_code)
);

CREATE INDEX idx_product_charges_product_code ON product_charges(product_code);

-- Customer Charge Overrides table
CREATE TABLE customer_charge_overrides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    charge_definition_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    override_amount DECIMAL(19,4),
    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    CONSTRAINT fk_customer_charge_overrides_charge_definition FOREIGN KEY (charge_definition_id) REFERENCES charge_definitions(id),
    CONSTRAINT uk_customer_charge_overrides_charge_customer UNIQUE (charge_definition_id, customer_id)
);

CREATE INDEX idx_customer_charge_overrides_customer_id ON customer_charge_overrides(customer_id);

-- Fee Waivers table
CREATE TABLE fee_waivers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    charge_definition_id BIGINT NOT NULL,
    scope VARCHAR(20) NOT NULL,
    reference_id VARCHAR(50) NOT NULL,
    waiver_percentage INTEGER NOT NULL DEFAULT 100,
    valid_from DATE NOT NULL,
    valid_to DATE,
    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    CONSTRAINT fk_fee_waivers_charge_definition FOREIGN KEY (charge_definition_id) REFERENCES charge_definitions(id)
);

CREATE INDEX idx_fee_waivers_scope_reference ON fee_waivers(scope, reference_id);
CREATE INDEX idx_fee_waivers_charge_definition_id ON fee_waivers(charge_definition_id);

-- Interest Rates table
CREATE TABLE interest_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    charge_definition_id BIGINT NOT NULL,
    product_code VARCHAR(50) NOT NULL,
    fixed_rate DECIMAL(10,6),
    accrual_schedule VARCHAR(20) NOT NULL DEFAULT 'DAILY',
    application_schedule VARCHAR(20) NOT NULL DEFAULT 'MONTHLY',
    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    CONSTRAINT fk_interest_rates_charge_definition FOREIGN KEY (charge_definition_id) REFERENCES charge_definitions(id)
);

CREATE INDEX idx_interest_rates_product_code ON interest_rates(product_code);

-- Interest Tiers table
CREATE TABLE interest_tiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interest_rate_id BIGINT NOT NULL,
    balance_from DECIMAL(19,4) NOT NULL,
    balance_to DECIMAL(19,4),
    rate DECIMAL(10,6) NOT NULL,
    CONSTRAINT fk_interest_tiers_interest_rate FOREIGN KEY (interest_rate_id) REFERENCES interest_rates(id) ON DELETE CASCADE
);

CREATE INDEX idx_interest_tiers_interest_rate_id ON interest_tiers(interest_rate_id);

-- Interest Accruals table
CREATE TABLE interest_accruals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interest_rate_id BIGINT NOT NULL,
    account_number VARCHAR(30) NOT NULL,
    accrual_date DATE NOT NULL,
    balance DECIMAL(19,4) NOT NULL,
    amount DECIMAL(19,6) NOT NULL,
    applied BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_interest_accruals_interest_rate FOREIGN KEY (interest_rate_id) REFERENCES interest_rates(id),
    CONSTRAINT uk_interest_accruals_rate_account_date UNIQUE (interest_rate_id, account_number, accrual_date)
);

CREATE INDEX idx_interest_accruals_account_number ON interest_accruals(account_number);
CREATE INDEX idx_interest_accruals_accrual_date ON interest_accruals(accrual_date);