-- V27__add_missing_user_columns.sql
-- Add columns required by User entity that were missing from V19.5

ALTER TABLE users ADD COLUMN user_type VARCHAR(50) NOT NULL DEFAULT 'INTERNAL';
ALTER TABLE users ADD COLUMN mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN mfa_secret VARCHAR(255);
ALTER TABLE users ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT 'system';
ALTER TABLE users ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ADD COLUMN updated_by VARCHAR(255);