-- V6__create_exchange_rates.sql
-- Create exchange_rates table for storing currency exchange rates

CREATE TABLE exchange_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_currency VARCHAR(3) NOT NULL REFERENCES currencies(code),
    target_currency VARCHAR(3) NOT NULL REFERENCES currencies(code),
    rate NUMERIC(19, 6) NOT NULL,
    effective_date DATE NOT NULL,
    created_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    CONSTRAINT uq_exchange_rates_base_target_date UNIQUE (base_currency, target_currency, effective_date)
);
