-- V7__create_holidays.sql
-- Create holidays table for storing country-specific holidays

CREATE TABLE holidays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code VARCHAR(2) NOT NULL REFERENCES countries(iso_code),
    holiday_date DATE NOT NULL,
    description TEXT,
    CONSTRAINT uq_holidays_country_date UNIQUE (country_code, holiday_date)
);
